"""
pipeline_advanced.py
Advanced ML Pipeline with Overfitting Prevention

Key improvements:
1. Temporal train/test split
2. Cross-validation
3. Multiple advanced algorithms
4. Regularization and feature selection
5. Overfitting detection
"""

import sys
from pathlib import Path

# Make project root importable
_root = Path(__file__).resolve().parent
sys.path.insert(0, str(_root))

from config.settings import settings
from src.models.train_advanced import (
    temporal_train_test_split,
    train_logistic_regression_advanced,
    train_random_forest_advanced,
    train_xgboost_advanced,
    train_lightgbm_advanced,
    train_catboost_advanced,
    detect_overfitting,
    save_model_advanced
)
from src.models.evaluate import evaluate_model, build_lift_table, save_evaluation_report

import pandas as pd
import numpy as np

PROCESSED_DIR = settings.PROCESSED_DATA_DIR
OUTPUT_DIR = settings.OUTPUT_DIR
MODELS_DIR = settings.MODEL_DIR


def main():
    print("=" * 70)
    print("🚀 ADVANCED ML PIPELINE - OVERFITTING PREVENTION")
    print("=" * 70)
    
    # Load existing feature matrix (generated by original pipeline)
    print("\n📊 Step 1: Loading feature matrix...")
    feature_matrix_path = PROCESSED_DIR / "feature_matrix.csv"
    
    if not feature_matrix_path.exists():
        print("  ❌ Feature matrix not found!")
        print("  Please run the original pipeline first: python pipeline.py")
        return
    
    feature_matrix = pd.read_csv(feature_matrix_path)
    print(f"  ✓ Loaded feature matrix: {len(feature_matrix)} rows, {len(feature_matrix.columns)} columns")
    
    # Step 2: Temporal train/test split (prevents data leakage)
    print("\n🔀 Step 2: Temporal train/test split...")
    X_train, X_test, y_train, y_test, feature_names = temporal_train_test_split(
        feature_matrix,
        target_col="will_purchase",
        test_ratio=0.20
    )
    
    # Step 3: Train multiple models with regularization
    print("\n🤖 Step 3: Training advanced models with regularization...")
    
    models = {}
    
    # Logistic Regression with L1/L2
    lr_model = train_logistic_regression_advanced(X_train, y_train, X_test, y_test)
    if lr_model:
        models['Logistic Regression'] = lr_model
    
    # Random Forest with regularization
    rf_model = train_random_forest_advanced(X_train, y_train, X_test, y_test)
    if rf_model:
        models['Random Forest'] = rf_model
    
    # XGBoost with regularization
    xgb_model = train_xgboost_advanced(X_train, y_train, X_test, y_test)
    if xgb_model:
        models['XGBoost'] = xgb_model
    
    # LightGBM with regularization
    lgbm_model = train_lightgbm_advanced(X_train, y_train, X_test, y_test)
    if lgbm_model:
        models['LightGBM'] = lgbm_model
    
    # CatBoost with regularization
    cb_model = train_catboost_advanced(X_train, y_train, X_test, y_test)
    if cb_model:
        models['CatBoost'] = cb_model
    
    # Step 4: Select best model based on test AUC
    print("\n📊 Step 4: Evaluating and selecting best model...")
    
    best_model = None
    best_model_name = None
    best_test_auc = 0
    
    results = {}
    
    for name, model in models.items():
        print(f"\n  Evaluating {name}...")
        
        # Evaluate on test set
        eval_results = evaluate_model(model, X_test, y_test, feature_names)
        results[name] = eval_results
        
        # Check overfitting
        overfit_check = detect_overfitting(model, X_train, X_test, y_train, y_test)
        
        print(f"    Test Accuracy:  {eval_results['accuracy']:.4f}")
        print(f"    Test Precision: {eval_results['precision']:.4f}")
        print(f"    Test Recall:    {eval_results['recall']:.4f}")
        print(f"    Test F1:        {eval_results['f1']:.4f}")
        print(f"    Test AUC-ROC:   {eval_results['auc_roc']:.4f}")
        print(f"    Train-Test Gap: {overfit_check['gaps']['auc_roc']:.4f}")
        
        if overfit_check['is_overfitted']:
            print(f"    ⚠️  Model is overfitted!")
        else:
            print(f"    ✓ Model generalizes well")
        
        # Select best model (highest test AUC with low overfitting)
        if eval_results['auc_roc'] > best_test_auc and not overfit_check['is_overfitted']:
            best_test_auc = eval_results['auc_roc']
            best_model = model
            best_model_name = name
    
    if best_model is None:
        # If all models are overfitted, pick the one with smallest gap
        print("\n  ⚠️  All models show overfitting. Selecting model with smallest gap...")
        min_gap = float('inf')
        for name, model in models.items():
            overfit_check = detect_overfitting(model, X_train, X_test, y_train, y_test)
            if overfit_check['gaps']['auc_roc'] < min_gap:
                min_gap = overfit_check['gaps']['auc_roc']
                best_model = model
                best_model_name = name
                best_test_auc = results[name]['auc_roc']
    
    print(f"\n✅ Best Model: {best_model_name}")
    print(f"   Test AUC-ROC: {best_test_auc:.4f}")
    
    # Step 5: Save best model
    print("\n💾 Step 5: Saving best model...")
    
    best_results = results[best_model_name]
    
    # Get feature importance
    feature_importance = {}
    if hasattr(best_model, 'feature_importances_'):
        feature_importance = dict(zip(feature_names, best_model.feature_importances_))
    elif hasattr(best_model, 'steps') and hasattr(best_model.steps[-1][1], 'feature_importances_'):
        feature_importance = dict(zip(feature_names, best_model.steps[-1][1].feature_importances_))
    elif hasattr(best_model, 'coef_'):
        feature_importance = dict(zip(feature_names, np.abs(best_model.coef_[0])))
    elif hasattr(best_model, 'steps') and hasattr(best_model.steps[-1][1], 'coef_'):
        feature_importance = dict(zip(feature_names, np.abs(best_model.steps[-1][1].coef_[0])))
    
    metadata = {
        "model_type": best_model_name,
        "target_col": "will_purchase",
        "n_features": len(feature_names),
        "feature_names": feature_names,
        "test_accuracy": float(best_results['accuracy']),
        "test_precision": float(best_results['precision']),
        "test_recall": float(best_results['recall']),
        "test_f1": float(best_results['f1']),
        "test_auc": float(best_results['auc_roc']),
        "training_method": "advanced_with_regularization",
        "split_method": "temporal",
        "test_size": 0.20
    }
    
    model_path = save_model_advanced(best_model, metadata, MODELS_DIR)
    print(f"  ✓ Model saved: {model_path}")
    
    # Step 6: Save evaluation report
    print("\n📈 Step 6: Saving evaluation report...")
    
    lift_df = build_lift_table(y_test, best_results['y_proba'])
    
    # Add y_test to results for ROC curve
    best_results['y_true'] = y_test
    
    dashboard_path = save_evaluation_report(
        best_results,
        lift_df,
        feature_importance,
        OUTPUT_DIR
    )
    print(f"  ✓ Dashboard data saved: {dashboard_path}")
    
    # Save feature names for API
    feature_names_path = OUTPUT_DIR / "feature_names.txt"
    feature_names_path.write_text("\n".join(feature_names))
    
    print("\n" + "=" * 70)
    print("✅ ADVANCED PIPELINE COMPLETE!")
    print("=" * 70)
    print(f"\n📊 Final Results:")
    print(f"   Model: {best_model_name}")
    print(f"   Test Accuracy:  {best_results['accuracy']:.4f}")
    print(f"   Test Precision: {best_results['precision']:.4f}")
    print(f"   Test Recall:    {best_results['recall']:.4f}")
    print(f"   Test F1:        {best_results['f1']:.4f}")
    print(f"   Test AUC-ROC:   {best_results['auc_roc']:.4f}")
    print(f"\n🎯 Model is ready for deployment!")
    print(f"\n💡 Restart the backend API to use the new model:")
    print(f"   The API will automatically load the latest model")


if __name__ == "__main__":
    main()
